apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yolo-dev
  name: yolo-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-dev
  template:
    metadata:
      labels:
        app: yolo-dev
    spec:
      containers:
      - env:
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: BUCKET_ID
              name: my-secrets-dev
        - name: QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: SQS_URL
              name: my-secrets-dev
        - name: POLYBOT_URL
          value: polybot-dev-service
        - name: STORAGE_TYPE
          value: dynamodb
        - name: DYNAMODB_SESSION
          value: majd_dev_prediction_session
        - name: DYNAMODB_OBJECTS
          value: majd_dev_detection_objects
        image: ghcr.io/majdabbas9/yolo_dev_image:58
        name: yolo-container
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 250m
