apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yolo-dev
  name: yolo-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-dev
  template:
    metadata:
      labels:
        app: yolo-dev
    spec:
      containers:
      - env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: TELEGRAM_TOKEN
              name: my-secrets-dev
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: BUCKET_ID
              name: my-secrets-dev
        - name: QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: SQS_URL
              name: my-secrets-dev
        - name: POLYBOT_URL
          value: polybot-service
        - name: STORAGE_TYPE
          value: dynamodb
        image: ghcr.io/majdabbas9/yolo_dev_image:52
        name: yolo-container
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
