apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: yolo-dev
  name: yolo-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-dev
  template:
    metadata:
      labels:
        app: yolo-dev
    spec:
      containers:
      - image: ghcr.io/majdabbas9/yolo_image:51
        name: yolo-container
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: TELEGRAM_TOKEN
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: BUCKET_ID
          - name: QUEUE_URL
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: SQS_URL
          - name: POLYBOT_URL
            value: "polybot-service"
          - name: STORAGE_TYPE
            value: "dynamodb"
