networks:
  monitoring_net:
    driver: bridge

services:
  prometheus:
    image: grafana/grafana
    container_name: mygrafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitoring_net


