networks:
  monitoring_net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana
    container_name: mygrafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
  prometheus:
    image: prom/prometheus
    container_name: myprometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    volumes:
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml


