version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: myprometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml