apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-dev
  labels:
    app: polybot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - name: polybot_container
        image: majdabbas99/polybot-dev-k8s
      - env:
          - ENVironment: "dev"