apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polybot-dev
  name: polybot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - image: majdabbas99/polybot_build_dev:188
        name: polybot_container
      - env:
        - ENVironment: dev
