apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: polybot-dev
  name: polybot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - image: ghcr.io/majdabbas9/telegram_bot_images:218
        name: polybot-container
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: TELEGRAM_TOKEN_DEV
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: DEV_BUCKET_ID
          - name: QUEUE_URL
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: DEV_SQS_URL
          - name: Nginx_url
            value: "majd.app.dev.fursa.click"

---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: dev
spec:
  selector:
    app: polybot-dev
  ports:
    - port: 8080         # Internal port (what Ingress sees)
      targetPort: 8443   # Your app's container port