apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polybot-dev
  name: polybot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - image: majdabbas99/polybot_dev:210
        name: polybot-container
---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot-dev
  ports:
    - port: 8080         # Internal port (what Ingress sees)
      targetPort: 8443   # Your app's container port