apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: polybot-dev
  name: polybot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - image: ghcr.io/majdabbas9/telegram_bot_images:219
        name: polybot-container
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: TELEGRAM_TOKEN
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: BUCKET_ID
          - name: QUEUE_URL
            valueFrom:
              secretKeyRef:
                name: my-secrets-dev
                key: SQS_URL
          - name: NGINX_URL
            value: "https://majd.app.dev.fursa.click"