apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polybot-dev
  name: polybot-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: TELEGRAM_TOKEN
              name: my-secrets-dev
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: BUCKET_ID
              name: my-secrets-dev
        - name: QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: SQS_URL
              name: my-secrets-dev
        - name: NGINX_URL
          value: https://majd.app.dev.fursa.click
        image: AQICAHgqsvSanZ7EmiTe/XdfTsU/osZD2tgE9q6r9812xkf/7AGnxgHykhWDGnekxFPGmFpsAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKenmQ5gZG4HFEC4QgIBEIBDKcLxyDcQ0LP0Yh/jkbJWs+JpMsFwFat+tUhqclYvZd+QQwQbtbbsSIPv1cFL6tppzWuGwegUV0tzxKstjgm88lJHzw==
        name: polybot-container
