apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/majdabbas9/polybot_infra'
    targetRevision: main
    path: polybot-k8s/yolo-dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true