global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otelcol'
    static_configs:
      - targets:
        - '10.0.0.180:8889'   # IP of yolo service instance
        - '10.0.0.203:8889'
        - '10.0.1.247:8889'
        - '10.0.1.43:8889'
