apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: prod
spec:
  selector:
    app: yolo-prod
  ports:
    - port: 8080         # Internal port (what Ingress sees)
      targetPort: 8080   # Your app's container port