apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  labels:
    app: yolo-prod
  name: yolo-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-prod
  template:
    metadata:
      labels:
        app: yolo-prod
    spec:
      containers:
      - image: ghcr.io/majdabbas9/yolo_image:51
        name: yolo-container
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets-prod
                key: TELEGRAM_TOKEN
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secrets-prod
                key: BUCKET_ID
          - name: QUEUE_URL
            valueFrom:
              secretKeyRef:
                name: my-secrets-prod
                key: SQS_URL
          - name: POLYBOT_URL
            value: "polybot-service"
          - name: STORAGE_TYPE
            value: "dynamodb"
