services:
  nginx:
    image: nginx
    container_name: mynginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ${NGINX_CONF_DST}:/etc/nginx/conf.d
      - ${CERTS_DIR}:/etc/nginx/ssl
