apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polybot-prod
  name: polybot-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-prod
  template:
    metadata:
      labels:
        app: polybot-prod
    spec:
      containers:
      - env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: TELEGRAM_TOKEN
              name: my-secrets-prod
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: BUCKET_ID
              name: my-secrets-prod
        - name: QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: SQS_URL
              name: my-secrets-prod
        - name: NGINX_URL
          value: https://majd.app.prod.fursa.click
        image: ghcr.io/majdabbas9/polybot_prod_image:18
        name: polybot-container
