apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  labels:
    app: polybot-prod
  name: polybot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-prod
  template:
    metadata:
      labels:
        app: polybot-prod
    spec:
      containers:
      - image: ghcr.io/majdabbas9/telegram_bot_images:219
        name: polybot-container
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets-prod
                key: TELEGRAM_TOKEN
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secrets-prod
                key: BUCKET_ID
          - name: QUEUE_URL
            valueFrom:
              secretKeyRef:
                name: my-secrets-prod
                key: SQS_URL
          - name: NGINX_URL
            value: "https://majd.app.prod.fursa.click"