version: '3.8'

networks:
  monitoring_net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: myprometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    volumes:
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml