name: Provision Infrastructure

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  provision:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform destroy -var-file=region.eu-west-1.tfvars --auto-approve
          # terraform apply -var-file=region.eu-west-1.tfvars --auto-approve
  init_control_plane:
    needs: provision
    uses: ./.github/workflows/init_control_plane.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_TOKEN_DEV: ${{ secrets.TELEGRAM_TOKEN_DEV }}
      PAT_GIT: ${{ secrets.PAT_GIT }}